// Word Groups Data - Pre-fragmented
// Each word is already broken into 5 fragments
// All fragments in each column position are guaranteed to be unique
const wordGroups = [
    {
        "theme": "MAGIC",
        "words": [
            [
                "S",
                "P",
                "E",
                "L",
                "L"
            ],
            [
                "W",
                "A",
                "N",
                "D",
                "S"
            ],
            [
                "C",
                "H",
                "A",
                "R",
                "M"
            ],
            [
                "T",
                "R",
                "I",
                "C",
                "K"
            ]
        ],
        "decoy": [
            "CA",
            "N",
            "Y",
            "O",
            "N"
        ]
    },
    {
        "theme": "MARSH",
        "words": [
            [
                "S",
                "W",
                "A",
                "M",
                "P"
            ],
            [
                "R",
                "E",
                "E",
                "D",
                "S"
            ],
            [
                "W",
                "A",
                "T",
                "E",
                "R"
            ],
            [
                "F",
                "R",
                "O",
                "G",
                "GY"
            ]
        ],
        "decoy": [
            "BR",
            "O",
            "N",
            "Z",
            "E"
        ]
    },
    {
        "theme": "DOLPHIN",
        "words": [
            [
                "O",
                "C",
                "E",
                "A",
                "N"
            ],
            [
                "J",
                "U",
                "M",
                "P",
                "S"
            ],
            [
                "PL",
                "A",
                "Y",
                "FU",
                "L"
            ],
            [
                "S",
                "M",
                "A",
                "R",
                "T"
            ]
        ],
        "decoy": [
            "C",
            "R",
            "I",
            "MS",
            "ON"
        ]
    },
    {
        "theme": "WESTEROS",
        "words": [
            [
                "S",
                "T",
                "A",
                "R",
                "K"
            ],
            [
                "DR",
                "A",
                "G",
                "O",
                "N"
            ],
            [
                "TH",
                "R",
                "O",
                "N",
                "E"
            ],
            [
                "T",
                "Y",
                "R",
                "I",
                "ON"
            ]
        ],
        "decoy": [
            "A",
            "N",
            "C",
            "H",
            "OR"
        ]
    },
    {
        "theme": "NOLAN",
        "words": [
            [
                "I",
                "NC",
                "EPT",
                "I",
                "ON"
            ],
            [
                "B",
                "A",
                "T",
                "MA",
                "N"
            ],
            [
                "IN",
                "TER",
                "STE",
                "LL",
                "AR"
            ],
            [
                "DUN",
                "K",
                "I",
                "R",
                "K"
            ]
        ],
        "decoy": [
            "EM",
            "ER",
            "A",
            "L",
            "D"
        ]
    },
    {
        "theme": "SPIELBERG",
        "words": [
            [
                "R",
                "A",
                "IDE",
                "R",
                "S"
            ],
            [
                "J",
                "UR",
                "AS",
                "SI",
                "C"
            ],
            [
                "SC",
                "HIN",
                "DL",
                "E",
                "R"
            ],
            [
                "S",
                "AV",
                "I",
                "N",
                "G"
            ]
        ],
        "decoy": [
            "MA",
            "R",
            "B",
            "L",
            "E"
        ]
    },
    {
        "theme": "ESPRESSO",
        "words": [
            [
                "C",
                "O",
                "F",
                "F",
                "EE"
            ],
            [
                "CA",
                "PP",
                "UC",
                "C",
                "INO"
            ],
            [
                "L",
                "A",
                "T",
                "T",
                "E"
            ],
            [
                "MA",
                "C",
                "C",
                "HIA",
                "TO"
            ]
        ],
        "decoy": [
            "V",
            "IO",
            "L",
            "E",
            "T"
        ]
    },
    {
        "theme": "SUSHI",
        "words": [
            [
                "S",
                "AL",
                "M",
                "O",
                "N"
            ],
            [
                "W",
                "A",
                "S",
                "A",
                "BI"
            ],
            [
                "N",
                "I",
                "G",
                "I",
                "RI"
            ],
            [
                "SA",
                "SH",
                "I",
                "M",
                "I"
            ]
        ],
        "decoy": [
            "TUR",
            "Q",
            "U",
            "OIS",
            "E"
        ]
    },
    {
        "theme": "MARVEL",
        "words": [
            [
                "I",
                "RO",
                "N",
                "M",
                "AN"
            ],
            [
                "SPI",
                "DE",
                "RM",
                "A",
                "N"
            ],
            [
                "A",
                "V",
                "E",
                "NGE",
                "RS"
            ],
            [
                "BLA",
                "C",
                "KPA",
                "NTH",
                "ER"
            ]
        ],
        "decoy": [
            "IN",
            "D",
            "I",
            "G",
            "O"
        ]
    },
    {
        "theme": "PIXAR",
        "words": [
            [
                "T",
                "O",
                "YS",
                "TO",
                "RY"
            ],
            [
                "MON",
                "ST",
                "ER",
                "SI",
                "NC"
            ],
            [
                "I",
                "NCR",
                "EDI",
                "BL",
                "ES"
            ],
            [
                "B",
                "R",
                "A",
                "V",
                "E"
            ]
        ],
        "decoy": [
            "M",
            "A",
            "G",
            "ENT",
            "A"
        ]
    },
    {
        "theme": "EINSTEIN",
        "words": [
            [
                "RE",
                "LA",
                "T",
                "IV",
                "ITY"
            ],
            [
                "EN",
                "E",
                "R",
                "G",
                "Y"
            ],
            [
                "T",
                "H",
                "E",
                "O",
                "RY"
            ],
            [
                "PH",
                "Y",
                "S",
                "I",
                "CS"
            ]
        ],
        "decoy": [
            "C",
            "OP",
            "P",
            "E",
            "R"
        ]
    },
    {
        "theme": "BASKETBALL",
        "words": [
            [
                "T",
                "R",
                "I",
                "PL",
                "E"
            ],
            [
                "DR",
                "I",
                "B",
                "B",
                "LE"
            ],
            [
                "R",
                "EBO",
                "U",
                "N",
                "D"
            ],
            [
                "L",
                "A",
                "Y",
                "U",
                "P"
            ]
        ],
        "decoy": [
            "P",
            "E",
            "A",
            "C",
            "H"
        ]
    },
    {
        "theme": "PIZZA",
        "words": [
            [
                "PE",
                "PP",
                "ER",
                "ON",
                "I"
            ],
            [
                "MOZ",
                "ZA",
                "R",
                "E",
                "LLA"
            ],
            [
                "M",
                "ARG",
                "HE",
                "RI",
                "TA"
            ],
            [
                "NE",
                "A",
                "PO",
                "LIT",
                "AN"
            ]
        ],
        "decoy": [
            "W",
            "H",
            "IS",
            "PE",
            "R"
        ]
    },
    {
        "theme": "MUSIC",
        "words": [
            [
                "SA",
                "X",
                "O",
                "PHO",
                "NE"
            ],
            [
                "TRU",
                "M",
                "P",
                "E",
                "T"
            ],
            [
                "B",
                "E",
                "B",
                "O",
                "P"
            ],
            [
                "S",
                "W",
                "I",
                "N",
                "G"
            ]
        ],
        "decoy": [
            "SC",
            "A",
            "R",
            "L",
            "ET"
        ]
    },
    {
        "theme": "HIMALAYA",
        "words": [
            [
                "E",
                "V",
                "ER",
                "ES",
                "T"
            ],
            [
                "S",
                "H",
                "E",
                "RP",
                "A"
            ],
            [
                "N",
                "E",
                "P",
                "A",
                "L"
            ],
            [
                "C",
                "L",
                "I",
                "M",
                "B"
            ]
        ],
        "decoy": [
            "D",
            "IA",
            "M",
            "ON",
            "D"
        ]
    },
    {
        "theme": "GREEK MYTHOLOGY",
        "words": [
            [
                "AP",
                "O",
                "L",
                "L",
                "O"
            ],
            [
                "A",
                "T",
                "H",
                "EN",
                "A"
            ],
            [
                "P",
                "OSE",
                "ID",
                "O",
                "N"
            ],
            [
                "JU",
                "P",
                "IT",
                "E",
                "R"
            ]
        ],
        "decoy": [
            "O",
            "LYM",
            "P",
            "U",
            "S"
        ]
    },
    {
        "theme": "EGYPTIAN",
        "words": [
            [
                "P",
                "HA",
                "RA",
                "O",
                "H"
            ],
            [
                "PY",
                "R",
                "A",
                "M",
                "ID"
            ],
            [
                "S",
                "P",
                "H",
                "I",
                "NX"
            ],
            [
                "C",
                "L",
                "EO",
                "PAT",
                "RA"
            ]
        ],
        "decoy": [
            "RU",
            "B",
            "I",
            "E",
            "S"
        ]
    },
    {
        "theme": "FRIENDS",
        "words": [
            [
                "R",
                "A",
                "C",
                "HE",
                "L"
            ],
            [
                "MO",
                "N",
                "I",
                "C",
                "A"
            ],
            [
                "PH",
                "O",
                "E",
                "B",
                "E"
            ],
            [
                "C",
                "H",
                "AND",
                "L",
                "ER"
            ]
        ],
        "decoy": [
            "A",
            "M",
            "B",
            "E",
            "R"
        ]
    },
    {
        "theme": "OFFICE",
        "words": [
            [
                "M",
                "IC",
                "H",
                "AE",
                "L"
            ],
            [
                "DW",
                "I",
                "G",
                "H",
                "T"
            ],
            [
                "SC",
                "H",
                "R",
                "UT",
                "E"
            ],
            [
                "D",
                "U",
                "N",
                "D",
                "ER"
            ]
        ],
        "decoy": [
            "J",
            "AS",
            "P",
            "E",
            "R"
        ]
    },
    {
        "theme": "BREAKFAST",
        "words": [
            [
                "P",
                "ANC",
                "AK",
                "E",
                "S"
            ],
            [
                "W",
                "AF",
                "F",
                "L",
                "E"
            ],
            [
                "OME",
                "L",
                "E",
                "T",
                "TE"
            ],
            [
                "B",
                "A",
                "C",
                "O",
                "N"
            ]
        ],
        "decoy": [
            "O",
            "PA",
            "L",
            "I",
            "NE"
        ]
    },
    {
        "theme": "WINERY",
        "words": [
            [
                "M",
                "E",
                "R",
                "L",
                "OT"
            ],
            [
                "C",
                "A",
                "B",
                "ERN",
                "ET"
            ],
            [
                "P",
                "I",
                "N",
                "O",
                "T"
            ],
            [
                "CHA",
                "RD",
                "ON",
                "N",
                "AY"
            ]
        ],
        "decoy": [
            "JA",
            "D",
            "EI",
            "T",
            "E"
        ]
    },
    {
        "theme": "JAPAN",
        "words": [
            [
                "T",
                "O",
                "K",
                "Y",
                "O"
            ],
            [
                "TE",
                "M",
                "P",
                "L",
                "E"
            ],
            [
                "S",
                "A",
                "MU",
                "RA",
                "I"
            ],
            [
                "K",
                "I",
                "M",
                "O",
                "NO"
            ]
        ],
        "decoy": [
            "OB",
            "SI",
            "DI",
            "A",
            "N"
        ]
    },
    {
        "theme": "DIVING",
        "words": [
            [
                "S",
                "C",
                "U",
                "B",
                "A"
            ],
            [
                "O",
                "X",
                "Y",
                "GE",
                "N"
            ],
            [
                "FLI",
                "P",
                "PE",
                "R",
                "S"
            ],
            [
                "D",
                "E",
                "P",
                "T",
                "H"
            ]
        ],
        "decoy": [
            "G",
            "A",
            "R",
            "NE",
            "T"
        ]
    },
    {
        "theme": "SAFARI",
        "words": [
            [
                "E",
                "LE",
                "P",
                "HAN",
                "T"
            ],
            [
                "G",
                "I",
                "RA",
                "FF",
                "E"
            ],
            [
                "S",
                "A",
                "V",
                "AN",
                "NA"
            ],
            [
                "Z",
                "E",
                "B",
                "R",
                "A"
            ]
        ],
        "decoy": [
            "C",
            "IT",
            "R",
            "I",
            "NE"
        ]
    },
    {
        "theme": "HOCKEY",
        "words": [
            [
                "S",
                "T",
                "I",
                "C",
                "K"
            ],
            [
                "P",
                "E",
                "N",
                "A",
                "LTY"
            ],
            [
                "SK",
                "A",
                "T",
                "IN",
                "G"
            ],
            [
                "G",
                "O",
                "A",
                "LI",
                "E"
            ]
        ],
        "decoy": [
            "TO",
            "U",
            "RMA",
            "L",
            "INE"
        ]
    },
    {
        "theme": "SUPERMAN",
        "words": [
            [
                "K",
                "R",
                "Y",
                "PT",
                "ON"
            ],
            [
                "M",
                "ETR",
                "O",
                "POL",
                "IS"
            ],
            [
                "C",
                "L",
                "A",
                "R",
                "K"
            ],
            [
                "SM",
                "ALL",
                "VI",
                "LL",
                "E"
            ]
        ],
        "decoy": [
            "Z",
            "I",
            "RC",
            "O",
            "N"
        ]
    },
    {
        "theme": "STARTREK",
        "words": [
            [
                "S",
                "P",
                "O",
                "C",
                "K"
            ],
            [
                "ENT",
                "E",
                "R",
                "PRI",
                "SE"
            ],
            [
                "VU",
                "L",
                "C",
                "A",
                "N"
            ],
            [
                "WA",
                "RPS",
                "P",
                "E",
                "ED"
            ]
        ],
        "decoy": [
            "I",
            "O",
            "L",
            "IT",
            "E"
        ]
    },
    {
        "theme": "TOLKIEN",
        "words": [
            [
                "F",
                "R",
                "O",
                "D",
                "O"
            ],
            [
                "G",
                "AN",
                "D",
                "A",
                "LF"
            ],
            [
                "M",
                "O",
                "R",
                "DO",
                "R"
            ],
            [
                "AR",
                "A",
                "G",
                "O",
                "RN"
            ]
        ],
        "decoy": [
            "K",
            "U",
            "NZI",
            "T",
            "E"
        ]
    },
    {
        "theme": "DISNEY",
        "words": [
            [
                "MI",
                "C",
                "K",
                "E",
                "Y"
            ],
            [
                "F",
                "R",
                "O",
                "Z",
                "EN"
            ],
            [
                "M",
                "O",
                "A",
                "N",
                "A"
            ],
            [
                "A",
                "L",
                "AD",
                "DI",
                "N"
            ]
        ],
        "decoy": [
            "S",
            "P",
            "I",
            "NE",
            "L"
        ]
    },
    {
        "theme": "APPLE",
        "words": [
            [
                "I",
                "P",
                "HO",
                "N",
                "E"
            ],
            [
                "MA",
                "C",
                "B",
                "O",
                "OK"
            ],
            [
                "AI",
                "R",
                "PO",
                "D",
                "S"
            ],
            [
                "W",
                "A",
                "T",
                "C",
                "H"
            ]
        ],
        "decoy": [
            "A",
            "Z",
            "U",
            "RI",
            "TE"
        ]
    },
    {
        "theme": "GOOGLE",
        "words": [
            [
                "S",
                "E",
                "AR",
                "C",
                "H"
            ],
            [
                "CH",
                "R",
                "O",
                "M",
                "E"
            ],
            [
                "AN",
                "D",
                "R",
                "O",
                "ID"
            ],
            [
                "Y",
                "O",
                "UT",
                "U",
                "BE"
            ]
        ],
        "decoy": [
            "MA",
            "L",
            "A",
            "CHI",
            "TE"
        ]
    },
    {
        "theme": "TESLA",
        "words": [
            [
                "P",
                "L",
                "A",
                "I",
                "D"
            ],
            [
                "ELE",
                "C",
                "T",
                "R",
                "IC"
            ],
            [
                "AU",
                "T",
                "O",
                "PI",
                "LOT"
            ],
            [
                "B",
                "A",
                "TT",
                "E",
                "RY"
            ]
        ],
        "decoy": [
            "RHO",
            "D",
            "ONI",
            "T",
            "E"
        ]
    },
    {
        "theme": "AQUARIUM",
        "words": [
            [
                "C",
                "O",
                "R",
                "A",
                "L"
            ],
            [
                "JE",
                "L",
                "LY",
                "FI",
                "SH"
            ],
            [
                "O",
                "C",
                "T",
                "OP",
                "US"
            ],
            [
                "DOL",
                "P",
                "H",
                "I",
                "N"
            ]
        ],
        "decoy": [
            "SUG",
            "I",
            "LI",
            "T",
            "E"
        ]
    },
    {
        "theme": "MARATHON",
        "words": [
            [
                "R",
                "U",
                "NN",
                "E",
                "R"
            ],
            [
                "F",
                "I",
                "N",
                "IS",
                "H"
            ],
            [
                "E",
                "NDU",
                "RA",
                "NC",
                "E"
            ],
            [
                "M",
                "E",
                "D",
                "A",
                "L"
            ]
        ],
        "decoy": [
            "TA",
            "NZ",
            "AN",
            "I",
            "TE"
        ]
    },
    {
        "theme": "CLIMBING",
        "words": [
            [
                "HA",
                "R",
                "NE",
                "S",
                "S"
            ],
            [
                "S",
                "U",
                "MM",
                "I",
                "T"
            ],
            [
                "B",
                "O",
                "U",
                "L",
                "DER"
            ],
            [
                "R",
                "A",
                "P",
                "PE",
                "L"
            ]
        ],
        "decoy": [
            "K",
            "EYB",
            "O",
            "A",
            "RD"
        ]
    },
    {
        "theme": "CAMPING",
        "words": [
            [
                "C",
                "A",
                "MP",
                "F",
                "IRE"
            ],
            [
                "S",
                "LE",
                "E",
                "PIN",
                "G"
            ],
            [
                "T",
                "R",
                "A",
                "I",
                "L"
            ],
            [
                "LA",
                "N",
                "T",
                "ER",
                "N"
            ]
        ],
        "decoy": [
            "PR",
            "I",
            "N",
            "T",
            "ER"
        ]
    },
    {
        "theme": "FISHING",
        "words": [
            [
                "T",
                "AC",
                "K",
                "L",
                "E"
            ],
            [
                "CA",
                "S",
                "TI",
                "N",
                "G"
            ],
            [
                "A",
                "N",
                "G",
                "LE",
                "R"
            ],
            [
                "H",
                "O",
                "O",
                "KI",
                "NG"
            ]
        ],
        "decoy": [
            "M",
            "A",
            "C",
            "H",
            "INE"
        ]
    },
    {
        "theme": "SAILING",
        "words": [
            [
                "A",
                "NC",
                "H",
                "O",
                "R"
            ],
            [
                "NA",
                "U",
                "T",
                "IC",
                "AL"
            ],
            [
                "VO",
                "Y",
                "A",
                "G",
                "E"
            ],
            [
                "C",
                "O",
                "MP",
                "AS",
                "S"
            ]
        ],
        "decoy": [
            "N",
            "E",
            "BU",
            "L",
            "A"
        ]
    },
    {
        "theme": "WRESTLING",
        "words": [
            [
                "G",
                "RA",
                "P",
                "P",
                "LE"
            ],
            [
                "TA",
                "KE",
                "DO",
                "W",
                "N"
            ],
            [
                "M",
                "A",
                "T",
                "C",
                "H"
            ],
            [
                "SU",
                "B",
                "MIS",
                "S",
                "ION"
            ]
        ],
        "decoy": [
            "P",
            "H",
            "OEN",
            "I",
            "X"
        ]
    },
    {
        "theme": "GYMNASTICS",
        "words": [
            [
                "V",
                "A",
                "U",
                "L",
                "T"
            ],
            [
                "F",
                "L",
                "O",
                "O",
                "R"
            ],
            [
                "R",
                "OU",
                "T",
                "I",
                "NE"
            ],
            [
                "B",
                "AL",
                "A",
                "NC",
                "E"
            ]
        ],
        "decoy": [
            "S",
            "PH",
            "I",
            "N",
            "X"
        ]
    },
    {
        "theme": "ARCHERY",
        "words": [
            [
                "A",
                "R",
                "R",
                "O",
                "W"
            ],
            [
                "T",
                "A",
                "RG",
                "E",
                "T"
            ],
            [
                "Q",
                "U",
                "I",
                "VE",
                "R"
            ],
            [
                "BU",
                "LLS",
                "E",
                "Y",
                "E"
            ]
        ],
        "decoy": [
            "Z",
            "E",
            "N",
            "IT",
            "H"
        ]
    },
    {
        "theme": "BASEBALL",
        "words": [
            [
                "PI",
                "TC",
                "H",
                "E",
                "R"
            ],
            [
                "HO",
                "M",
                "E",
                "RU",
                "N"
            ],
            [
                "D",
                "I",
                "A",
                "MO",
                "ND"
            ],
            [
                "S",
                "T",
                "R",
                "I",
                "KE"
            ]
        ],
        "decoy": [
            "P",
            "R",
            "I",
            "S",
            "M"
        ]
    },
    {
        "theme": "FOOTBALL",
        "words": [
            [
                "TOU",
                "C",
                "H",
                "DOW",
                "N"
            ],
            [
                "QUA",
                "RT",
                "ERB",
                "AC",
                "K"
            ],
            [
                "T",
                "A",
                "C",
                "K",
                "LE"
            ],
            [
                "F",
                "I",
                "E",
                "L",
                "D"
            ]
        ],
        "decoy": [
            "M",
            "IR",
            "R",
            "O",
            "R"
        ]
    },
    {
        "theme": "CRICKET",
        "words": [
            [
                "W",
                "IC",
                "K",
                "E",
                "T"
            ],
            [
                "B",
                "O",
                "W",
                "LE",
                "R"
            ],
            [
                "C",
                "E",
                "NT",
                "U",
                "RY"
            ],
            [
                "P",
                "I",
                "T",
                "C",
                "H"
            ]
        ],
        "decoy": [
            "L",
            "A",
            "NTE",
            "R",
            "N"
        ]
    },
    {
        "theme": "GOLFER",
        "words": [
            [
                "D",
                "R",
                "I",
                "V",
                "ER"
            ],
            [
                "P",
                "U",
                "TT",
                "E",
                "R"
            ],
            [
                "B",
                "I",
                "R",
                "DI",
                "E"
            ],
            [
                "C",
                "A",
                "D",
                "D",
                "Y"
            ]
        ],
        "decoy": [
            "S",
            "T",
            "A",
            "T",
            "UE"
        ]
    },
    {
        "theme": "NASCAR",
        "words": [
            [
                "DRA",
                "FT",
                "I",
                "N",
                "G"
            ],
            [
                "STO",
                "CK",
                "C",
                "A",
                "R"
            ],
            [
                "V",
                "ICT",
                "O",
                "R",
                "Y"
            ],
            [
                "SPE",
                "E",
                "D",
                "W",
                "AY"
            ]
        ],
        "decoy": [
            "S",
            "T",
            "AR",
            "DUS",
            "T"
        ]
    },
    {
        "theme": "HIPHOP",
        "words": [
            [
                "B",
                "R",
                "E",
                "A",
                "K"
            ],
            [
                "FR",
                "E",
                "ES",
                "T",
                "YLE"
            ],
            [
                "BA",
                "T",
                "T",
                "L",
                "E"
            ],
            [
                "C",
                "IP",
                "H",
                "E",
                "R"
            ]
        ],
        "decoy": [
            "G",
            "LA",
            "C",
            "I",
            "ER"
        ]
    },
    {
        "theme": "SALSA",
        "words": [
            [
                "RH",
                "Y",
                "T",
                "H",
                "M"
            ],
            [
                "P",
                "AR",
                "TN",
                "E",
                "R"
            ],
            [
                "D",
                "A",
                "N",
                "C",
                "E"
            ],
            [
                "T",
                "E",
                "M",
                "P",
                "O"
            ]
        ],
        "decoy": [
            "F",
            "AL",
            "C",
            "O",
            "N"
        ]
    },
    {
        "theme": "OPERA",
        "words": [
            [
                "SO",
                "P",
                "RA",
                "N",
                "O"
            ],
            [
                "S",
                "T",
                "A",
                "G",
                "E"
            ],
            [
                "TH",
                "EA",
                "T",
                "E",
                "R"
            ],
            [
                "OV",
                "E",
                "R",
                "T",
                "URE"
            ]
        ],
        "decoy": [
            "T",
            "A",
            "L",
            "O",
            "N"
        ]
    },
    {
        "theme": "SYMPHONY",
        "words": [
            [
                "O",
                "RC",
                "H",
                "EST",
                "RA"
            ],
            [
                "CO",
                "NDU",
                "C",
                "T",
                "OR"
            ],
            [
                "MOV",
                "EM",
                "E",
                "N",
                "T"
            ],
            [
                "S",
                "C",
                "O",
                "R",
                "E"
            ]
        ],
        "decoy": [
            "MO",
            "UN",
            "T",
            "AI",
            "N"
        ]
    },
    {
        "theme": "GUITAR",
        "words": [
            [
                "ST",
                "R",
                "I",
                "N",
                "G"
            ],
            [
                "A",
                "C",
                "OUS",
                "T",
                "IC"
            ],
            [
                "C",
                "H",
                "O",
                "R",
                "D"
            ],
            [
                "M",
                "E",
                "LO",
                "D",
                "Y"
            ]
        ],
        "decoy": [
            "AV",
            "ALA",
            "N",
            "C",
            "HE"
        ]
    },
    {
        "theme": "VIOLIN",
        "words": [
            [
                "ST",
                "R",
                "I",
                "N",
                "G"
            ],
            [
                "CON",
                "CE",
                "R",
                "T",
                "O"
            ],
            [
                "M",
                "EL",
                "O",
                "D",
                "Y"
            ],
            [
                "V",
                "I",
                "B",
                "R",
                "ATO"
            ]
        ],
        "decoy": [
            "C",
            "AN",
            "D",
            "L",
            "E"
        ]
    },
    {
        "theme": "FLUTIST",
        "words": [
            [
                "WOO",
                "D",
                "W",
                "IN",
                "D"
            ],
            [
                "E",
                "M",
                "BO",
                "UCH",
                "URE"
            ],
            [
                "F",
                "I",
                "N",
                "GE",
                "R"
            ],
            [
                "ME",
                "L",
                "O",
                "D",
                "Y"
            ]
        ],
        "decoy": [
            "P",
            "YT",
            "H",
            "O",
            "N"
        ]
    },
    {
        "theme": "BANJO",
        "words": [
            [
                "S",
                "T",
                "R",
                "I",
                "NG"
            ],
            [
                "BLU",
                "E",
                "G",
                "RA",
                "SS"
            ],
            [
                "T",
                "W",
                "A",
                "N",
                "G"
            ],
            [
                "P",
                "L",
                "U",
                "C",
                "K"
            ]
        ],
        "decoy": [
            "SE",
            "R",
            "E",
            "NAD",
            "E"
        ]
    },
    {
        "theme": "SHREK",
        "words": [
            [
                "FA",
                "IR",
                "Y",
                "TA",
                "LE"
            ],
            [
                "D",
                "O",
                "N",
                "KE",
                "Y"
            ],
            [
                "S",
                "W",
                "A",
                "M",
                "P"
            ],
            [
                "F",
                "I",
                "O",
                "N",
                "A"
            ]
        ],
        "decoy": [
            "M",
            "E",
            "D",
            "A",
            "L"
        ]
    },
    {
        "theme": "TERMINATOR",
        "words": [
            [
                "CY",
                "B",
                "O",
                "R",
                "G"
            ],
            [
                "S",
                "A",
                "R",
                "A",
                "H"
            ],
            [
                "C",
                "O",
                "NN",
                "O",
                "R"
            ],
            [
                "SK",
                "Y",
                "N",
                "E",
                "T"
            ]
        ],
        "decoy": [
            "M",
            "AR",
            "B",
            "L",
            "E"
        ]
    },
    {
        "theme": "BREAKING BAD",
        "words": [
            [
                "W",
                "AL",
                "T",
                "E",
                "R"
            ],
            [
                "ME",
                "T",
                "HL",
                "A",
                "B"
            ],
            [
                "J",
                "E",
                "SS",
                "I",
                "E"
            ],
            [
                "HEI",
                "S",
                "E",
                "NB",
                "ERG"
            ]
        ],
        "decoy": [
            "G",
            "U",
            "I",
            "T",
            "AR"
        ]
    },
    {
        "theme": "STRANGER THINGS",
        "words": [
            [
                "E",
                "L",
                "E",
                "VE",
                "N"
            ],
            [
                "DEM",
                "O",
                "GO",
                "RG",
                "ON"
            ],
            [
                "H",
                "AW",
                "K",
                "IN",
                "S"
            ],
            [
                "UP",
                "SI",
                "DE",
                "DO",
                "WN"
            ]
        ],
        "decoy": [
            "M",
            "A",
            "R",
            "B",
            "LE"
        ]
    },
    {
        "theme": "SOPRANOS",
        "words": [
            [
                "BA",
                "DA",
                "B",
                "I",
                "NG"
            ],
            [
                "MO",
                "B",
                "S",
                "TE",
                "R"
            ],
            [
                "TH",
                "ER",
                "A",
                "P",
                "Y"
            ],
            [
                "C",
                "A",
                "RM",
                "EL",
                "A"
            ]
        ],
        "decoy": [
            "V",
            "I",
            "O",
            "LI",
            "N"
        ]
    },
    {
        "theme": "WITCHER",
        "words": [
            [
                "G",
                "E",
                "R",
                "AL",
                "T"
            ],
            [
                "MO",
                "NS",
                "T",
                "E",
                "R"
            ],
            [
                "S",
                "W",
                "O",
                "R",
                "D"
            ],
            [
                "YE",
                "N",
                "NE",
                "F",
                "ER"
            ]
        ],
        "decoy": [
            "B",
            "R",
            "A",
            "I",
            "N"
        ]
    },
    {
        "theme": "GAME OF THRONES",
        "words": [
            [
                "S",
                "T",
                "A",
                "R",
                "K"
            ],
            [
                "DR",
                "A",
                "G",
                "O",
                "N"
            ],
            [
                "TH",
                "R",
                "O",
                "N",
                "E"
            ],
            [
                "T",
                "Y",
                "R",
                "I",
                "ON"
            ]
        ],
        "decoy": [
            "A",
            "N",
            "C",
            "H",
            "OR"
        ]
    },
    {
        "theme": "WALKING DEAD",
        "words": [
            [
                "ZO",
                "M",
                "B",
                "I",
                "ES"
            ],
            [
                "R",
                "I",
                "C",
                "K",
                "SS"
            ],
            [
                "W",
                "A",
                "L",
                "KE",
                "R"
            ],
            [
                "G",
                "RI",
                "M",
                "E",
                "S"
            ]
        ],
        "decoy": [
            "B",
            "R",
            "A",
            "NC",
            "H"
        ]
    },
    {
        "theme": "QUEEN",
        "words": [
            [
                "FR",
                "E",
                "D",
                "D",
                "IE"
            ],
            [
                "G",
                "LA",
                "M",
                "RO",
                "CK"
            ],
            [
                "B",
                "O",
                "H",
                "EM",
                "IAN"
            ],
            [
                "GA",
                "L",
                "IL",
                "E",
                "O"
            ]
        ],
        "decoy": [
            "V",
            "I",
            "O",
            "L",
            "IN"
        ]
    },
    {
        "theme": "POKEMON",
        "words": [
            [
                "PIK",
                "A",
                "C",
                "H",
                "U"
            ],
            [
                "A",
                "S",
                "H",
                "E",
                "N"
            ],
            [
                "P",
                "OK",
                "EB",
                "A",
                "LL"
            ],
            [
                "G",
                "Y",
                "M",
                "S",
                "S"
            ]
        ],
        "decoy": [
            "V",
            "I",
            "O",
            "L",
            "IN"
        ]
    },
    {
        "theme": "MINECRAFT",
        "words": [
            [
                "S",
                "T",
                "E",
                "V",
                "E"
            ],
            [
                "B",
                "LO",
                "C",
                "K",
                "S"
            ],
            [
                "C",
                "R",
                "EEP",
                "E",
                "R"
            ],
            [
                "D",
                "I",
                "AM",
                "ON",
                "D"
            ]
        ],
        "decoy": [
            "M",
            "A",
            "R",
            "B",
            "LE"
        ]
    },
    {
        "theme": "MARIO KART",
        "words": [
            [
                "R",
                "A",
                "C",
                "E",
                "R"
            ],
            [
                "S",
                "H",
                "EL",
                "L",
                "S"
            ],
            [
                "B",
                "AN",
                "A",
                "N",
                "A"
            ],
            [
                "D",
                "R",
                "I",
                "F",
                "T"
            ]
        ],
        "decoy": [
            "C",
            "L",
            "O",
            "U",
            "D"
        ]
    },
    {
        "theme": "CALL OF DUTY",
        "words": [
            [
                "WA",
                "R",
                "F",
                "AR",
                "E"
            ],
            [
                "M",
                "O",
                "DE",
                "R",
                "N"
            ],
            [
                "S",
                "N",
                "I",
                "PE",
                "R"
            ],
            [
                "G",
                "H",
                "O",
                "S",
                "T"
            ]
        ],
        "decoy": [
            "P",
            "I",
            "A",
            "N",
            "O"
        ]
    },
    {
        "theme": "WOLVERINE",
        "words": [
            [
                "L",
                "O",
                "G",
                "A",
                "N"
            ],
            [
                "C",
                "L",
                "A",
                "W",
                "S"
            ],
            [
                "A",
                "DA",
                "MA",
                "NT",
                "IUM"
            ],
            [
                "H",
                "EA",
                "L",
                "I",
                "NG"
            ]
        ],
        "decoy": [
            "B",
            "RA",
            "N",
            "C",
            "H"
        ]
    },
    {
        "theme": "DEADPOOL",
        "words": [
            [
                "SA",
                "R",
                "CA",
                "ST",
                "IC"
            ],
            [
                "WI",
                "L",
                "S",
                "O",
                "N"
            ],
            [
                "MER",
                "C",
                "EN",
                "AR",
                "Y"
            ],
            [
                "CHI",
                "MI",
                "CH",
                "AN",
                "GAS"
            ]
        ],
        "decoy": [
            "V",
            "I",
            "O",
            "L",
            "IN"
        ]
    },
    {
        "theme": "THOR",
        "words": [
            [
                "H",
                "A",
                "M",
                "ME",
                "R"
            ],
            [
                "M",
                "J",
                "O",
                "L",
                "NIR"
            ],
            [
                "A",
                "S",
                "G",
                "A",
                "RD"
            ],
            [
                "W",
                "O",
                "R",
                "T",
                "HY"
            ]
        ],
        "decoy": [
            "P",
            "I",
            "A",
            "N",
            "O"
        ]
    },
    {
        "theme": "AQUAMAN",
        "words": [
            [
                "TE",
                "LE",
                "P",
                "AT",
                "HY"
            ],
            [
                "BL",
                "ACK",
                "MA",
                "NT",
                "A"
            ],
            [
                "TR",
                "ID",
                "E",
                "N",
                "T"
            ],
            [
                "AT",
                "LA",
                "NT",
                "I",
                "S"
            ]
        ],
        "decoy": [
            "B",
            "R",
            "A",
            "NC",
            "H"
        ]
    },
    {
        "theme": "BLACK PANTHER",
        "words": [
            [
                "T",
                "CH",
                "A",
                "L",
                "LA"
            ],
            [
                "W",
                "A",
                "KA",
                "N",
                "DA"
            ],
            [
                "V",
                "IB",
                "RA",
                "NIU",
                "M"
            ],
            [
                "S",
                "H",
                "U",
                "R",
                "I"
            ]
        ],
        "decoy": [
            "M",
            "I",
            "X",
            "E",
            "R"
        ]
    },
    {
        "theme": "DRAGON BALL",
        "words": [
            [
                "PI",
                "C",
                "C",
                "O",
                "LO"
            ],
            [
                "K",
                "AME",
                "HAM",
                "E",
                "HA"
            ],
            [
                "S",
                "A",
                "I",
                "Y",
                "AN"
            ],
            [
                "V",
                "EG",
                "E",
                "T",
                "A"
            ]
        ],
        "decoy": [
            "B",
            "R",
            "AN",
            "C",
            "H"
        ]
    },
    {
        "theme": "DEMON SLAYER",
        "words": [
            [
                "TA",
                "N",
                "J",
                "I",
                "RO"
            ],
            [
                "S",
                "W",
                "O",
                "R",
                "D"
            ],
            [
                "BRE",
                "AT",
                "HI",
                "N",
                "G"
            ],
            [
                "N",
                "E",
                "Z",
                "UK",
                "O"
            ]
        ],
        "decoy": [
            "M",
            "A",
            "RB",
            "L",
            "E"
        ]
    },
    {
        "theme": "FULLMETAL ALCHEMIST",
        "words": [
            [
                "ED",
                "W",
                "A",
                "R",
                "D"
            ],
            [
                "E",
                "L",
                "R",
                "I",
                "C"
            ],
            [
                "ALC",
                "H",
                "E",
                "M",
                "Y"
            ],
            [
                "T",
                "RAN",
                "SM",
                "UT",
                "E"
            ]
        ],
        "decoy": [
            "BR",
            "A",
            "N",
            "C",
            "H"
        ]
    },
    {
        "theme": "TWILIGHT",
        "words": [
            [
                "B",
                "E",
                "L",
                "L",
                "A"
            ],
            [
                "ED",
                "W",
                "A",
                "R",
                "D"
            ],
            [
                "VA",
                "M",
                "P",
                "I",
                "RE"
            ],
            [
                "C",
                "U",
                "LL",
                "E",
                "N"
            ]
        ],
        "decoy": [
            "BR",
            "A",
            "N",
            "C",
            "H"
        ]
    },
    {
        "theme": "CHRONICLES OF NARNIA",
        "words": [
            [
                "A",
                "S",
                "L",
                "A",
                "N"
            ],
            [
                "W",
                "AR",
                "D",
                "R",
                "OBE"
            ],
            [
                "P",
                "EVE",
                "N",
                "SI",
                "E"
            ],
            [
                "C",
                "A",
                "SP",
                "I",
                "AN"
            ]
        ],
        "decoy": [
            "B",
            "R",
            "A",
            "NC",
            "H"
        ]
    },
    {
        "theme": "PERCY JACKSON",
        "words": [
            [
                "D",
                "E",
                "M",
                "IG",
                "OD"
            ],
            [
                "P",
                "OS",
                "E",
                "ID",
                "ON"
            ],
            [
                "OL",
                "YM",
                "P",
                "U",
                "S"
            ],
            [
                "A",
                "NNA",
                "B",
                "E",
                "TH"
            ]
        ],
        "decoy": [
            "V",
            "I",
            "OL",
            "I",
            "N"
        ]
    },
    {
        "theme": "YOUTUBE",
        "words": [
            [
                "SU",
                "BS",
                "C",
                "RI",
                "BE"
            ],
            [
                "V",
                "L",
                "O",
                "G",
                "S"
            ],
            [
                "M",
                "ON",
                "ET",
                "IZ",
                "E"
            ],
            [
                "ALG",
                "OR",
                "I",
                "TH",
                "M"
            ]
        ],
        "decoy": [
            "B",
            "R",
            "AN",
            "C",
            "H"
        ]
    },
    {
        "theme": "SPOTIFY",
        "words": [
            [
                "P",
                "LA",
                "YL",
                "IS",
                "T"
            ],
            [
                "SH",
                "UF",
                "F",
                "L",
                "E"
            ],
            [
                "PR",
                "E",
                "M",
                "IU",
                "M"
            ],
            [
                "W",
                "R",
                "AP",
                "PE",
                "D"
            ]
        ],
        "decoy": [
            "V",
            "I",
            "OL",
            "I",
            "N"
        ]
    },
    {
        "theme": "SPONGEBOB",
        "words": [
            [
                "PA",
                "T",
                "R",
                "IC",
                "K"
            ],
            [
                "SQ",
                "U",
                "IDW",
                "AR",
                "D"
            ],
            [
                "K",
                "R",
                "A",
                "B",
                "S"
            ],
            [
                "P",
                "L",
                "ANK",
                "T",
                "ON"
            ]
        ],
        "decoy": [
            "M",
            "AR",
            "B",
            "L",
            "E"
        ]
    },
    {
        "theme": "RICK MORTY",
        "words": [
            [
                "P",
                "O",
                "R",
                "T",
                "AL"
            ],
            [
                "PI",
                "C",
                "K",
                "L",
                "E"
            ],
            [
                "SC",
                "H",
                "W",
                "IF",
                "TY"
            ],
            [
                "ME",
                "E",
                "SE",
                "EK",
                "S"
            ]
        ],
        "decoy": [
            "BR",
            "A",
            "N",
            "C",
            "H"
        ]
    },
    {
        "theme": "FUTURAMA",
        "words": [
            [
                "B",
                "EN",
                "D",
                "E",
                "R"
            ],
            [
                "L",
                "E",
                "E",
                "L",
                "A"
            ],
            [
                "P",
                "L",
                "A",
                "N",
                "ET"
            ],
            [
                "EX",
                "P",
                "R",
                "ES",
                "S"
            ]
        ],
        "decoy": [
            "V",
            "I",
            "OL",
            "I",
            "N"
        ]
    },
    {
        "theme": "LEGEND KORRA",
        "words": [
            [
                "AV",
                "A",
                "T",
                "A",
                "R"
            ],
            [
                "BE",
                "N",
                "DI",
                "N",
                "G"
            ],
            [
                "RE",
                "P",
                "U",
                "BLI",
                "C"
            ],
            [
                "A",
                "S",
                "A",
                "M",
                "I"
            ]
        ],
        "decoy": [
            "B",
            "RA",
            "N",
            "C",
            "H"
        ]
    },
    {
        "theme": "CASTLEVANIA",
        "words": [
            [
                "DR",
                "A",
                "C",
                "U",
                "LA"
            ],
            [
                "T",
                "R",
                "E",
                "VO",
                "R"
            ],
            [
                "S",
                "Y",
                "P",
                "H",
                "A"
            ],
            [
                "A",
                "LU",
                "CA",
                "R",
                "D"
            ]
        ],
        "decoy": [
            "V",
            "I",
            "OL",
            "I",
            "N"
        ]
    },
    {
        "theme": "SANDMAN",
        "words": [
            [
                "MO",
                "R",
                "P",
                "HE",
                "US"
            ],
            [
                "DR",
                "E",
                "A",
                "M",
                "S"
            ],
            [
                "EN",
                "D",
                "L",
                "E",
                "SS"
            ],
            [
                "D",
                "ES",
                "I",
                "R",
                "E"
            ]
        ],
        "decoy": [
            "M",
            "A",
            "R",
            "B",
            "LE"
        ]
    },
    {
        "theme": "COBRA KAI",
        "words": [
            [
                "K",
                "A",
                "RA",
                "T",
                "E"
            ],
            [
                "D",
                "AN",
                "I",
                "E",
                "L"
            ],
            [
                "JO",
                "H",
                "N",
                "N",
                "Y"
            ],
            [
                "M",
                "I",
                "G",
                "U",
                "EL"
            ]
        ],
        "decoy": [
            "V",
            "IO",
            "L",
            "I",
            "N"
        ]
    },
    {
        "theme": "PEAKY BLINDERS",
        "words": [
            [
                "T",
                "H",
                "O",
                "MA",
                "S"
            ],
            [
                "S",
                "HE",
                "L",
                "B",
                "Y"
            ],
            [
                "BIR",
                "MI",
                "N",
                "GHA",
                "M"
            ],
            [
                "R",
                "A",
                "Z",
                "O",
                "R"
            ]
        ],
        "decoy": [
            "MA",
            "R",
            "B",
            "L",
            "E"
        ]
    },
    {
        "theme": "TED LASSO",
        "words": [
            [
                "C",
                "O",
                "A",
                "C",
                "H"
            ],
            [
                "R",
                "IC",
                "H",
                "M",
                "OND"
            ],
            [
                "B",
                "E",
                "L",
                "I",
                "EVE"
            ],
            [
                "FOO",
                "T",
                "B",
                "A",
                "LL"
            ]
        ],
        "decoy": [
            "M",
            "A",
            "R",
            "BL",
            "E"
        ]
    },
    {
        "theme": "SQUID GAMES",
        "words": [
            [
                "P",
                "LA",
                "Y",
                "E",
                "R"
            ],
            [
                "G",
                "U",
                "A",
                "R",
                "D"
            ],
            [
                "M",
                "A",
                "R",
                "B",
                "LE"
            ],
            [
                "B",
                "RI",
                "D",
                "G",
                "E"
            ]
        ],
        "decoy": [
            "V",
            "I",
            "O",
            "L",
            "IN"
        ]
    },
    {
        "theme": "HOUSE DRAGON",
        "words": [
            [
                "T",
                "AR",
                "GA",
                "RY",
                "EN"
            ],
            [
                "DA",
                "E",
                "M",
                "O",
                "N"
            ],
            [
                "R",
                "HA",
                "EN",
                "YR",
                "A"
            ],
            [
                "V",
                "I",
                "SE",
                "R",
                "YS"
            ]
        ],
        "decoy": [
            "MA",
            "R",
            "B",
            "L",
            "E"
        ]
    },
    {
        "theme": "RINGS OF POWER",
        "words": [
            [
                "GAL",
                "AD",
                "R",
                "I",
                "EL"
            ],
            [
                "EL",
                "R",
                "O",
                "N",
                "D"
            ],
            [
                "N",
                "UM",
                "EN",
                "O",
                "R"
            ],
            [
                "S",
                "A",
                "U",
                "RO",
                "N"
            ]
        ],
        "decoy": [
            "B",
            "RA",
            "N",
            "C",
            "H"
        ]
    },
    {
        "theme": "WHITE LOTUS",
        "words": [
            [
                "R",
                "E",
                "SO",
                "R",
                "T"
            ],
            [
                "T",
                "A",
                "N",
                "Y",
                "A"
            ],
            [
                "P",
                "O",
                "R",
                "T",
                "IA"
            ],
            [
                "E",
                "T",
                "H",
                "A",
                "N"
            ]
        ],
        "decoy": [
            "B",
            "R",
            "A",
            "N",
            "CH"
        ]
    },
    {
        "theme": "LOKI",
        "words": [
            [
                "S",
                "Y",
                "L",
                "VI",
                "E"
            ],
            [
                "M",
                "O",
                "BI",
                "U",
                "S"
            ],
            [
                "TI",
                "M",
                "E",
                "L",
                "Y"
            ],
            [
                "V",
                "A",
                "RIA",
                "N",
                "T"
            ]
        ],
        "decoy": [
            "B",
            "R",
            "AN",
            "C",
            "H"
        ]
    },
    {
        "theme": "FRIENDS",
        "words": [
            [
                "R",
                "A",
                "C",
                "HE",
                "L"
            ],
            [
                "MO",
                "N",
                "I",
                "C",
                "A"
            ],
            [
                "PH",
                "O",
                "E",
                "B",
                "E"
            ],
            [
                "C",
                "HAN",
                "D",
                "L",
                "ER"
            ]
        ],
        "decoy": [
            "V",
            "I",
            "OL",
            "I",
            "N"
        ]
    },
    {
        "theme": "OFFICE",
        "words": [
            [
                "MIC",
                "H",
                "A",
                "E",
                "L"
            ],
            [
                "DW",
                "I",
                "G",
                "H",
                "T"
            ],
            [
                "S",
                "C",
                "HR",
                "U",
                "TE"
            ],
            [
                "D",
                "U",
                "N",
                "DE",
                "R"
            ]
        ],
        "decoy": [
            "M",
            "A",
            "R",
            "B",
            "LE"
        ]
    },
    {
        "theme": "PARKS REC",
        "words": [
            [
                "L",
                "E",
                "S",
                "L",
                "IE"
            ],
            [
                "K",
                "N",
                "O",
                "P",
                "E"
            ],
            [
                "S",
                "W",
                "ANS",
                "O",
                "N"
            ],
            [
                "P",
                "ERK",
                "I",
                "N",
                "S"
            ]
        ],
        "decoy": [
            "BR",
            "A",
            "N",
            "C",
            "H"
        ]
    },
    {
        "theme": "COMMUNITY",
        "words": [
            [
                "S",
                "T",
                "U",
                "D",
                "Y"
            ],
            [
                "G",
                "R",
                "O",
                "U",
                "P"
            ],
            [
                "GRE",
                "E",
                "NDA",
                "L",
                "E"
            ],
            [
                "W",
                "IN",
                "G",
                "E",
                "R"
            ]
        ],
        "decoy": [
            "M",
            "A",
            "R",
            "B",
            "LE"
        ]
    },
    {
        "theme": "VEEP",
        "words": [
            [
                "SE",
                "L",
                "I",
                "N",
                "A"
            ],
            [
                "M",
                "E",
                "Y",
                "E",
                "R"
            ],
            [
                "ERI",
                "C",
                "S",
                "S",
                "ON"
            ],
            [
                "S",
                "P",
                "LE",
                "T",
                "T"
            ]
        ],
        "decoy": [
            "V",
            "I",
            "OL",
            "I",
            "N"
        ]
    }
];
